### ISSUE TITLE
Running into error when running python script

### ISSUE THREAD

**Issue by samtfischer** [jslay88/pyhap_vesync#3]
When I run the vesync app.py I get this error: ImportError: No module named pyhap.accessory_driver

**Comment by jslay88** [comment]
Make sure you are using the correct version of `HAP-python`, and that you have it installed.

    pip uninstall HAP-python -y
    pip install -U -r requirements.txt -y

**Comment by samtfischer** [comment]
I've tried uninstalling HAP-python and reinstalling it with

*pip install -U -r requirements.txt* and it looks to reinstall it
successfully, but I still get the same error.


If I run what you sent: *pip install -U -r requirements.txt -y*
it returns an error saying that -y isn't an option.


Thanks,
Sam Fischer

**Comment by jslay88** [comment]
I recommend going to something that is still maintained, as the API has completely changed from when I last built/updated this script, and I no longer use these outlets myself.

https://github.com/markperdue/pyvesync
